language: ruby
notifications:
  email: false
rvm:
  - 2.3.1
cache:
  - bundler
  - apt
addons:
  postgresql: '9.5'
before_script:
  - bundle exec rake db:setup
script:
  - bundle exec cucumber
  - bundle exec rspec
